version: 0.2
phases:
  install:
    commands:
      - cd 01api
      - aws cloudformation package --template-file petstore-api.yaml
                                   --s3-bucket postman-api
                                   --s3-prefix api-code
                                   --output-template-file petstore-api-output.yaml
                                   --no-fail-on-empty-changeset
artifacts:
  type: zip
  files:
    - 01api/petstore-api-output.yaml
